# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone X",
  "iPhone 6 Plus",
  "iPhone 6",
  "iPad Pro (12.9-inch)",
#   "iPad Pro (9.7-inch)",
#   "Apple TV 1080p"
])

languages([
  "en-US",
  "de-DE"
])

# The name of the scheme which contains the UI Tests
scheme "IntuneMAMTestApp"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
#project "./../IntuneMAMTestApp.xcodeproj"
# workspace "./Project.xcworkspace"

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
